import React from 'react';

const AppMain = () => (
    <main className="main-stage">
        <div className="container">
            <p className="paragraph">
                {'I am a paragraph that is generated by the main area of the app component. I have one big brother, App header and my little bro is the footer. Oh and a nephew too at some point, the sidebar'}
            </p>
        </div>
    </main>
);

export default AppMain;
